// Built-in offline drug guide.
// A curated dataset of the most commonly used prescription medications,
// over-the-counter products and supplements, bundled with the app so a
// medication can be captured with NO internet connection.
//
// Field names mirror the Medication entity, so a guide entry can flow
// straight into the confirm form and be saved to the local library.
//
// This is general reference information for common products — always follow
// your doctor or pharmacist's instructions and the actual product label.

export const DRUGS = [
  // ---------- Prescription: cholesterol / heart / blood pressure ----------
  { name: "Lipitor", generic_name: "Atorvastatin", category: "prescription", aliases: ["atorvastatin calcium"], active_ingredients: ["Atorvastatin"], dose: "10–80 mg", form: "Tablet", frequency: "Once daily", route: "Oral", purpose: "Lowers LDL cholesterol and the risk of heart attack and stroke", side_effects: ["Muscle or joint pain", "Headache", "Diarrhea"], warnings: ["Avoid grapefruit juice", "Tell your doctor about unexplained muscle pain or weakness", "Not for use in pregnancy"], storage: "Room temperature, away from moisture", manufacturer: "Pfizer" },
  { name: "Crestor", generic_name: "Rosuvastatin", category: "prescription", active_ingredients: ["Rosuvastatin"], dose: "5–40 mg", form: "Tablet", frequency: "Once daily", route: "Oral", purpose: "Lowers LDL cholesterol and triglycerides", side_effects: ["Headache", "Muscle aches", "Nausea"], warnings: ["Avoid grapefruit juice", "Report unexplained muscle pain or weakness"], manufacturer: "AstraZeneca" },
  { name: "Zocor", generic_name: "Simvastatin", category: "prescription", active_ingredients: ["Simvastatin"], dose: "5–40 mg", form: "Tablet", frequency: "Once daily in the evening", route: "Oral", purpose: "Lowers LDL cholesterol", side_effects: ["Headache", "Muscle aches", "Stomach upset"], warnings: ["Avoid grapefruit juice", "Report unexplained muscle pain or weakness"], manufacturer: "Merck" },
  { name: "Lisinopril", generic_name: "Lisinopril", category: "prescription", aliases: ["zestril", "prinivil"], active_ingredients: ["Lisinopril"], dose: "2.5–40 mg", form: "Tablet", frequency: "Once daily", route: "Oral", purpose: "Treats high blood pressure and heart failure, protects the kidneys", side_effects: ["Dry cough", "Dizziness", "Headache"], warnings: ["Do not use in pregnancy", "Can raise potassium — avoid salt substitutes with potassium"] },
  { name: "Norvasc", generic_name: "Amlodipine", category: "prescription", active_ingredients: ["Amlodipine"], dose: "2.5–10 mg", form: "Tablet", frequency: "Once daily", route: "Oral", purpose: "Treats high blood pressure and chest pain (angina)", side_effects: ["Ankle swelling", "Flushing", "Headache"], warnings: ["Grapefruit may increase side effects"] },
  { name: "Cozaar", generic_name: "Losartan", category: "prescription", active_ingredients: ["Losartan potassium"], dose: "25–100 mg", form: "Tablet", frequency: "Once or twice daily", route: "Oral", purpose: "Treats high blood pressure and protects the kidneys in diabetes", side_effects: ["Dizziness", "Tiredness"], warnings: ["Do not use in pregnancy"] },
  { name: "Toprol XL", generic_name: "Metoprolol succinate", category: "prescription", aliases: ["lopressor", "metoprolol tartrate"], active_ingredients: ["Metoprolol"], dose: "25–200 mg", form: "Extended-release tablet", frequency: "Once daily", route: "Oral", purpose: "Treats high blood pressure, chest pain and heart failure", side_effects: ["Tiredness", "Slow heartbeat", "Cold hands or feet"], warnings: ["Do not stop suddenly — taper with your doctor", "May mask low blood sugar in diabetics"] },
  { name: "Coreg", generic_name: "Carvedilol", category: "prescription", active_ingredients: ["Carvedilol"], dose: "3.125–25 mg", form: "Tablet", frequency: "Twice daily with food", route: "Oral", purpose: "Treats heart failure and high blood pressure", side_effects: ["Dizziness", "Tiredness", "Low blood pressure"], warnings: ["Do not stop suddenly — taper with your doctor"] },
  { name: "Hydrochlorothiazide", generic_name: "Hydrochlorothiazide", category: "prescription", aliases: ["hctz", "microzide"], active_ingredients: ["Hydrochlorothiazide"], dose: "12.5–50 mg", form: "Tablet", frequency: "Once daily in the morning", route: "Oral", purpose: "Water pill that lowers blood pressure and treats swelling", side_effects: ["Frequent urination", "Dizziness", "Sun sensitivity"], warnings: ["Can lower potassium and sodium", "Take in the morning to avoid night urination"] },
  { name: "Lasix", generic_name: "Furosemide", category: "prescription", active_ingredients: ["Furosemide"], dose: "20–80 mg", form: "Tablet", frequency: "Once or twice daily", route: "Oral", purpose: "Water pill that treats fluid build-up (edema) from heart, liver or kidney problems", side_effects: ["Frequent urination", "Dizziness", "Muscle cramps"], warnings: ["Can lower potassium", "Expect increased urination for a few hours"] },
  { name: "Aldactone", generic_name: "Spironolactone", category: "prescription", active_ingredients: ["Spironolactone"], dose: "25–100 mg", form: "Tablet", frequency: "Once or twice daily", route: "Oral", purpose: "Potassium-sparing water pill for heart failure, high blood pressure and hormonal conditions", side_effects: ["Breast tenderness", "Increased potassium", "Dizziness"], warnings: ["Avoid potassium supplements and salt substitutes"] },

  // ---------- Prescription: thyroid / diabetes ----------
  { name: "Synthroid", generic_name: "Levothyroxine", category: "prescription", aliases: ["levoxyl", "euthyrox", "levothyroxine sodium"], active_ingredients: ["Levothyroxine (T4)"], dose: "25–300 mcg", form: "Tablet", frequency: "Once daily on an empty stomach", route: "Oral", purpose: "Replaces thyroid hormone in hypothyroidism (underactive thyroid)", side_effects: ["Temporary hair loss in the first months", "Weight change", "Trouble sleeping if the dose is too high"], warnings: ["Take 30–60 minutes before breakfast, at the same time daily", "Keep the same brand — doses are not always interchangeable"], manufacturer: "AbbVie" },
  { name: "Glucophage", generic_name: "Metformin", category: "prescription", aliases: ["metformin hcl", "glucophage xr"], active_ingredients: ["Metformin hydrochloride"], dose: "500–1000 mg", form: "Tablet", frequency: "Once or twice daily with meals", route: "Oral", purpose: "First-choice medicine for type 2 diabetes; lowers blood sugar", side_effects: ["Stomach upset", "Diarrhea", "Metallic taste"], warnings: ["Take with food to reduce stomach upset", "Stop before contrast-dye scans/surgery as directed by your doctor"] },
  { name: "Glucotrol", generic_name: "Glipizide", category: "prescription", active_ingredients: ["Glipizide"], dose: "5–10 mg", form: "Tablet", frequency: "Once daily, 30 minutes before breakfast", route: "Oral", purpose: "Lowers blood sugar in type 2 diabetes", side_effects: ["Low blood sugar", "Nausea", "Weight gain"], warnings: ["Know the signs of low blood sugar (sweating, shaking, confusion)", "Avoid skipping meals"] },
  { name: "Jardiance", generic_name: "Empagliflozin", category: "prescription", active_ingredients: ["Empagliflozin"], dose: "10–25 mg", form: "Tablet", frequency: "Once daily in the morning", route: "Oral", purpose: "Lowers blood sugar and protects the heart and kidneys in type 2 diabetes", side_effects: ["Urinary tract or genital infections", "Increased urination", "Thirst"], warnings: ["Stay hydrated", "Seek urgent care for nausea/vomiting with very high sugar (ketoacidosis risk)"] },
  { name: "Januvia", generic_name: "Sitagliptin", category: "prescription", active_ingredients: ["Sitagliptin"], dose: "25–100 mg", form: "Tablet", frequency: "Once daily", route: "Oral", purpose: "Lowers blood sugar in type 2 diabetes", side_effects: ["Headache", "Sore throat", "Stomach upset"], warnings: ["Report severe joint pain or blistering rash"] },
  { name: "Lantus", generic_name: "Insulin glargine", category: "prescription", aliases: ["basaglar", "toujeo", "lantus soloestar"], active_ingredients: ["Insulin glargine"], dose: "Units as prescribed", form: "Prefilled pen (injection)", frequency: "Once daily at bedtime", route: "Subcutaneous injection", purpose: "Long-acting insulin that controls blood sugar overnight and between meals", side_effects: ["Low blood sugar", "Injection-site reactions", "Weight gain"], warnings: ["Never share pens or needles", "Do not dilute or mix with other insulins", "Know the signs of low blood sugar"] },

  // ---------- Prescription: stomach / acid ----------
  { name: "Nexium 24HR", generic_name: "Esomeprazole", category: "otc", aliases: ["esomeprazole magnesium", "nexium"], active_ingredients: ["Esomeprazole"], dose: "20 mg", form: "Delayed-release capsule", frequency: "Once daily before breakfast (14-day course)", route: "Oral", purpose: "Treats frequent heartburn (GERD) by reducing stomach acid", side_effects: ["Headache", "Diarrhea", "Gas"], warnings: ["Do not use for more than 14 days without a doctor", "Long-term use may lower magnesium and B12"] },
  { name: "Protonix", generic_name: "Pantoprazole", category: "prescription", active_ingredients: ["Pantoprazole"], dose: "20–40 mg", form: "Delayed-release tablet", frequency: "Once daily", route: "Oral", purpose: "Treats GERD, erosive esophagitis and reduces stomach ulcers from NSAIDs", side_effects: ["Headache", "Diarrhea", "Nausea"], warnings: ["Long-term use may lower magnesium and B12"] },

  // ---------- Prescription: mental health / sleep / nerves ----------
  { name: "Zoloft", generic_name: "Sertraline", category: "prescription", active_ingredients: ["Sertraline"], dose: "25–200 mg", form: "Tablet", frequency: "Once daily", route: "Oral", purpose: "Treats depression, anxiety, OCD and PTSD", side_effects: ["Nausea", "Trouble sleeping", "Sexual side effects"], warnings: ["Do not combine with MAO inhibitors", "Report worsening mood or suicidal thoughts immediately"] },
  { name: "Lexapro", generic_name: "Escitalopram", category: "prescription", active_ingredients: ["Escitalopram"], dose: "5–20 mg", form: "Tablet", frequency: "Once daily", route: "Oral", purpose: "Treats depression and generalized anxiety", side_effects: ["Nausea", "Drowsiness", "Trouble sleeping"], warnings: ["Do not combine with MAO inhibitors", "Report worsening mood immediately"] },
  { name: "Prozac", generic_name: "Fluoxetine", category: "prescription", active_ingredients: ["Fluoxetine"], dose: "10–20 mg", form: "Capsule", frequency: "Once daily in the morning", route: "Oral", purpose: "Treats depression, OCD, bulimia and panic disorder", side_effects: ["Nausea", "Trouble sleeping", "Decreased appetite"], warnings: ["Do not combine with MAO inhibitors", "May take 4–6 weeks to feel the full effect"] },
  { name: "Effexor XR", generic_name: "Venlafaxine", category: "prescription", active_ingredients: ["Venlafaxine"], dose: "37.5–225 mg", form: "Extended-release capsule", frequency: "Once daily", route: "Oral", purpose: "Treats depression, anxiety and panic disorder", side_effects: ["Nausea", "Dry mouth", "Increased blood pressure at higher doses"], warnings: ["Do not stop suddenly — taper with your doctor"] },
  { name: "Cymbalta", generic_name: "Duloxetine", category: "prescription", active_ingredients: ["Duloxetine"], dose: "20–60 mg", form: "Delayed-release capsule", frequency: "Once or twice daily", route: "Oral", purpose: "Treats depression, anxiety, and nerve pain (including diabetic nerve pain and fibromyalgia)", side_effects: ["Nausea", "Dry mouth", "Sleepiness"], warnings: ["Do not combine with MAO inhibitors", "Do not use with heavy alcohol use or liver disease"] },
  { name: "Wellbutrin XL", generic_name: "Bupropion", category: "prescription", active_ingredients: ["Bupropion"], dose: "150–450 mg", form: "Extended-release tablet", frequency: "Once daily in the morning", route: "Oral", purpose: "Treats depression and seasonal affective disorder; also used for smoking cessation (as Zyban)", side_effects: ["Trouble sleeping", "Dry mouth", "Headache"], warnings: ["Do not crush or chew extended-release tablets", "Not for people with seizure disorders or eating disorders"] },
  { name: "Trazodone", generic_name: "Trazodone", category: "prescription", active_ingredients: ["Trazodone"], dose: "50–100 mg", form: "Tablet", frequency: "Once daily at bedtime", route: "Oral", purpose: "Treats depression; often used at low doses for sleep", side_effects: ["Drowsiness", "Dizziness", "Dry mouth"], warnings: ["May cause dizziness when standing — rise slowly", "Report prolonged or painful erections immediately"] },
  { name: "Xanax", generic_name: "Alprazolam", category: "prescription", active_ingredients: ["Alprazolam"], dose: "0.25–0.5 mg", form: "Tablet", frequency: "As prescribed (2–3 times daily)", route: "Oral", purpose: "Treats anxiety and panic disorder", side_effects: ["Drowsiness", "Dizziness", "Memory problems"], warnings: ["Controlled substance — habit forming; do not combine with alcohol or opioids", "Do not stop suddenly — taper with your doctor"] },
  { name: "Ativan", generic_name: "Lorazepam", category: "prescription", active_ingredients: ["Lorazepam"], dose: "0.5–2 mg", form: "Tablet", frequency: "As prescribed (2–3 times daily)", route: "Oral", purpose: "Treats anxiety; also used before procedures for sedation", side_effects: ["Drowsiness", "Dizziness", "Weakness"], warnings: ["Controlled substance — habit forming; do not combine with alcohol or opioids"] },
  { name: "Ambien", generic_name: "Zolpidem", category: "prescription", active_ingredients: ["Zolpidem tartrate"], dose: "5–10 mg", form: "Tablet", frequency: "Once at bedtime, only when you can sleep 7+ hours", route: "Oral", purpose: "Treats short-term insomnia (trouble falling asleep)", side_effects: ["Drowsiness the next day", "Dizziness", "Sleep-walking or doing activities while not fully awake"], warnings: ["Take right before bed — never drive after taking", "Do not combine with alcohol", "Short-term use only; habit forming"] },
  { name: "Neurontin", generic_name: "Gabapentin", category: "prescription", aliases: ["gabapentin enacarbil", "gralise", "horizant"], active_ingredients: ["Gabapentin"], dose: "100–800 mg", form: "Capsule", frequency: "Three times daily", route: "Oral", purpose: "Treats nerve pain and seizures; also used for shingles pain", side_effects: ["Drowsiness", "Dizziness", "Swelling of legs"], warnings: ["Do not drive until you know how it affects you", "Do not stop suddenly"] },
  { name: "Lyrica", generic_name: "Pregabalin", category: "prescription", active_ingredients: ["Pregabalin"], dose: "25–150 mg", form: "Capsule", frequency: "Twice or three times daily", route: "Oral", purpose: "Treats nerve pain from diabetes, shingles, spinal injury and fibromyalgia", side_effects: ["Dizziness", "Sleepiness", "Swelling of hands and feet"], warnings: ["Controlled substance — may be habit forming", "Do not drive until you know how it affects you"] },

  // ---------- Prescription: steroids / antibiotics ----------
  { name: "Prednisone", generic_name: "Prednisone", category: "prescription", active_ingredients: ["Prednisone"], dose: "5–60 mg (often tapered)", form: "Tablet", frequency: "Once daily in the morning, with food", route: "Oral", purpose: "Corticosteroid that reduces inflammation in asthma flares, arthritis, allergies and autoimmune conditions", side_effects: ["Increased appetite", "Trouble sleeping", "Mood changes"], warnings: ["Take with food", "Do not stop suddenly — taper exactly as prescribed", "Raises blood sugar and blood pressure"] },
  { name: "Amoxicillin", generic_name: "Amoxicillin", category: "prescription", active_ingredients: ["Amoxicillin"], dose: "250–500 mg", form: "Capsule or suspension", frequency: "Every 8 hours", route: "Oral", purpose: "Penicillin antibiotic for ear, sinus, throat, urinary and dental infections", side_effects: ["Diarrhea", "Nausea", "Rash"], warnings: ["Tell your doctor about any penicillin allergy", "Finish the full course even if you feel better"] },
  { name: "Augmentin", generic_name: "Amoxicillin/clavulanate", category: "prescription", active_ingredients: ["Amoxicillin", "Clavulanate potassium"], dose: "875/125 mg", form: "Tablet", frequency: "Twice daily with food", route: "Oral", purpose: "Penicillin combination antibiotic for sinus, lung, skin and urinary infections", side_effects: ["Diarrhea", "Nausea", "Yeast infection"], warnings: ["Take with food to reduce stomach upset", "Finish the full course"] },
  { name: "Zithromax", generic_name: "Azithromycin", category: "prescription", aliases: ["z-pak", "azithromycin dose pack"], active_ingredients: ["Azithromycin"], dose: "250 mg", form: "Tablet or suspension", frequency: "Once daily for 3–5 days (Z-pak)", route: "Oral", purpose: "Macrolide antibiotic for respiratory, skin and ear infections", side_effects: ["Diarrhea", "Stomach pain", "Nausea"], warnings: ["Report pounding or irregular heartbeat", "Take antacids 2 hours apart from doses"] },
  { name: "Keflex", generic_name: "Cephalexin", category: "prescription", aliases: ["cephalexin monohydrate"], active_ingredients: ["Cephalexin"], dose: "250–500 mg", form: "Capsule", frequency: "Four times daily", route: "Oral", purpose: "Cephalosporin antibiotic for skin, bone, ear and urinary infections", side_effects: ["Diarrhea", "Stomach upset", "Rash"], warnings: ["Tell your doctor about any penicillin allergy", "Finish the full course"] },
  { name: "Doxycycline", generic_name: "Doxycycline hyclate", category: "prescription", aliases: ["doxycycline monohydrate", "vibramycin"], active_ingredients: ["Doxycycline"], dose: "100 mg", form: "Capsule or tablet", frequency: "Twice daily", route: "Oral", purpose: "Tetracycline antibiotic for acne, respiratory and tick-borne infections", side_effects: ["Sun sensitivity", "Nausea", "Heartburn"], warnings: ["Take with a full glass of water and stay upright 30 minutes", "Do not take with dairy, antacids or iron (2 hours apart)", "Use sunscreen"] },
  { name: "Cipro", generic_name: "Ciprofloxacin", category: "prescription", aliases: ["ciprofloxacin hcl", "ciprofloxacin er"], active_ingredients: ["Ciprofloxacin"], dose: "250–750 mg", form: "Tablet", frequency: "Twice daily", route: "Oral", purpose: "Fluoroquinolone antibiotic for urinary tract and other infections", side_effects: ["Nausea", "Diarrhea", "Dizziness"], warnings: ["Avoid dairy, antacids and vitamins with iron/zinc within 2 hours", "Rarely causes tendon problems — stop and call your doctor for tendon pain", "Tell your doctor if you take tizanidine"] },

  // ---------- Prescription: blood thinners ----------
  { name: "Coumadin", generic_name: "Warfarin", category: "prescription", aliases: ["jantoven"], active_ingredients: ["Warfarin sodium"], dose: "Individualized by INR blood test", form: "Tablet", frequency: "Once daily at the same time", route: "Oral", purpose: "Prevents harmful blood clots in atrial fibrillation, DVT and after valve replacement", side_effects: ["Bleeding or bruising", "Nausea"], warnings: ["Keep vitamin K intake (leafy greens) consistent", "Many drug interactions — tell every doctor and dentist you take it", "Never change the dose on your own"] },
  { name: "Eliquis", generic_name: "Apixaban", category: "prescription", active_ingredients: ["Apixaban"], dose: "2.5–5 mg", form: "Tablet", frequency: "Twice daily", route: "Oral", purpose: "Prevents stroke in atrial fibrillation and treats/prevents blood clots", side_effects: ["Bleeding or bruising", "Nausea"], warnings: ["Do not stop without your doctor — stopping raises stroke risk", "Tell every doctor and dentist you take it"] },
  { name: "Xarelto", generic_name: "Rivaroxaban", category: "prescription", active_ingredients: ["Rivaroxaban"], dose: "10–20 mg", form: "Tablet", frequency: "Once daily with the evening meal (per indication)", route: "Oral", purpose: "Prevents stroke in atrial fibrillation and treats/prevents blood clots", side_effects: ["Bleeding or bruising", "Itching"], warnings: ["Take with food for 15–20 mg doses", "Do not stop without your doctor"] },
  { name: "Plavix", generic_name: "Clopidogrel", category: "prescription", aliases: ["clopidogrel bisulfate"], active_ingredients: ["Clopidogrel"], dose: "75 mg", form: "Tablet", frequency: "Once daily", route: "Oral", purpose: "Prevents heart attack and stroke in people with stents or artery disease", side_effects: ["Bruising", "Bleeding", "Stomach upset"], warnings: ["Do not stop before surgery without your doctor", "Avoid omeprazole unless your doctor approves"] },

  // ---------- Prescription: lungs / pain / other ----------
  { name: "Ventolin HFA", generic_name: "Albuterol", category: "prescription", aliases: ["proair hfa", "proventil hfa", "salbutamol"], active_ingredients: ["Albuterol sulfate"], dose: "90 mcg per actuation", form: "Inhaler (aerosol)", frequency: "2 puffs every 4–6 hours as needed", route: "Inhalation", purpose: "Quick-relief inhaler that opens airways during asthma attacks or exercise", side_effects: ["Fast heartbeat", "Shakiness", "Headache"], warnings: ["If you need it more than twice a week, tell your doctor", "Rinse mouth after use"] },
  { name: "Singulair", generic_name: "Montelukast", category: "prescription", active_ingredients: ["Montelukast sodium"], dose: "10 mg", form: "Tablet", frequency: "Once daily in the evening", route: "Oral", purpose: "Prevents asthma attacks and relieves seasonal allergy symptoms", side_effects: ["Headache", "Stomach pain"], warnings: ["Report mood changes, agitation or sleep problems — a boxed warning exists"] },
  { name: "Flexeril", generic_name: "Cyclobenzaprine", category: "prescription", aliases: ["amrix"], active_ingredients: ["Cyclobenzaprine"], dose: "5–10 mg", form: "Tablet", frequency: "Three times daily", route: "Oral", purpose: "Muscle relaxant for short-term relief of muscle spasms (2–3 weeks)", side_effects: ["Drowsiness", "Dry mouth", "Dizziness"], warnings: ["Do not drive until you know how it affects you", "Do not combine with alcohol", "Avoid in the elderly"] },
  { name: "Percocet", generic_name: "Oxycodone/acetaminophen", category: "prescription", active_ingredients: ["Oxycodone", "Acetaminophen"], dose: "5/325 mg", form: "Tablet", frequency: "Every 6 hours as needed", route: "Oral", purpose: "Short-term relief of moderate to severe pain", side_effects: ["Drowsiness", "Constipation", "Nausea"], warnings: ["Controlled substance — habit forming; never share", "Do not combine with other acetaminophen (Tylenol) products", "Do not combine with alcohol or sedatives"] },
  { name: "Norco", generic_name: "Hydrocodone/acetaminophen", category: "prescription", aliases: ["vicodin", "lorcet"], active_ingredients: ["Hydrocodone bitartrate", "Acetaminophen"], dose: "5–10/325 mg", form: "Tablet", frequency: "Every 4–6 hours as needed", route: "Oral", purpose: "Short-term relief of moderate to severe pain", side_effects: ["Drowsiness", "Constipation", "Nausea"], warnings: ["Controlled substance — habit forming; never share", "Do not combine with other acetaminophen products", "Do not combine with alcohol or sedatives"] },
  { name: "Ultram", generic_name: "Tramadol", category: "prescription", aliases: ["tramadol hcl", "conzip"], active_ingredients: ["Tramadol"], dose: "50–100 mg", form: "Tablet", frequency: "Every 4–6 hours as needed (max 400 mg/day)", route: "Oral", purpose: "Relief of moderate to moderately severe pain", side_effects: ["Nausea", "Dizziness", "Drowsiness"], warnings: ["Controlled substance — can be habit forming", "Lowers the seizure threshold", "Never combine with SSRIs, MAO inhibitors or alcohol without medical advice"] },
  { name: "Flomax", generic_name: "Tamsulosin", category: "prescription", aliases: ["tamsulosin hcl"], active_ingredients: ["Tamsulosin"], dose: "0.4 mg", form: "Capsule", frequency: "Once daily, 30 minutes after the same meal daily", route: "Oral", purpose: "Relieves urinary symptoms of an enlarged prostate (BPH)", side_effects: ["Dizziness on standing", "Abnormal ejaculation", "Runny nose"], warnings: ["Rise slowly to avoid fainting", "Tell your eye surgeon before cataract surgery"] },
  { name: "Zofran", generic_name: "Ondansetron", category: "prescription", aliases: ["ondansetron hcl", "zofran odt"], active_ingredients: ["Ondansetron"], dose: "4–8 mg", form: "Tablet or dissolvable tablet (ODT)", frequency: "Every 8 hours as needed", route: "Oral", purpose: "Prevents nausea and vomiting from chemotherapy, radiation or surgery", side_effects: ["Headache", "Constipation", "Tiredness"], warnings: ["Rarely changes heart rhythm — tell your doctor about heart conditions"] },
  { name: "Vistaril", generic_name: "Hydroxyzine", category: "prescription", aliases: ["atarax", "hydroxyzine hcl", "hydroxyzine pamotate"], active_ingredients: ["Hydroxyzine"], dose: "25–100 mg", form: "Tablet or capsule", frequency: "Three to four times daily as needed", route: "Oral", purpose: "Antihistamine that relieves anxiety, itching and allergic reactions", side_effects: ["Drowsiness", "Dry mouth", "Dizziness"], warnings: ["Do not drive until you know how it affects you", "Avoid alcohol"] },

  // ---------- OTC: pain / fever ----------
  { name: "Tylenol", generic_name: "Acetaminophen", category: "otc", aliases: ["paracetamol", "tylenol extra strength", "mapap"], active_ingredients: ["Acetaminophen"], dose: "325–650 mg (max 3000 mg/day)", form: "Tablet, caplet or liquid", frequency: "Every 4–6 hours as needed", route: "Oral", purpose: "Relieves pain and reduces fever; gentler on the stomach than NSAIDs", side_effects: ["Rare at correct doses"], warnings: ["Severe liver damage if you take more than directed or drink alcohol heavily", "Check other medicines for hidden acetaminophen (cold/flu combos)", "Maximum 3000 mg per day unless your doctor says otherwise"] },
  { name: "Advil", generic_name: "Ibuprofen", category: "otc", aliases: ["motrin", "ibuprofen", "nurofen", "advil liqui-gels"], active_ingredients: ["Ibuprofen"], dose: "200–400 mg (max 1200 mg/day OTC)", form: "Tablet, caplet or liquid gel", frequency: "Every 6–8 hours as needed", route: "Oral", purpose: "NSAID that relieves pain, fever and inflammation (headaches, muscle aches, cramps, arthritis)", side_effects: ["Stomach upset", "Heartburn", "Dizziness"], warnings: ["Take with food or milk", "Can cause stomach bleeding — avoid with alcohol", "Ask your doctor before use if you take blood thinners, have kidney disease or high blood pressure", "Avoid in the third trimester of pregnancy"] },
  { name: "Aleve", generic_name: "Naproxen sodium", category: "otc", aliases: ["naproxen", "midol extended relief"], active_ingredients: ["Naproxen sodium"], dose: "220 mg (max 660 mg/day OTC)", form: "Tablet or caplet", frequency: "Every 8–12 hours as needed", route: "Oral", purpose: "Long-acting NSAID for pain, fever, cramps and arthritis", side_effects: ["Stomach upset", "Heartburn", "Fluid retention"], warnings: ["Take with food", "Lasts longer than ibuprofen — do not double up", "Ask your doctor before use with blood thinners or kidney disease"] },
  { name: "Bayer Aspirin", generic_name: "Aspirin", category: "otc", aliases: ["acetylsalicylic acid", "aspirin", "ecotrin", "bayer low dose"], active_ingredients: ["Aspirin (acetylsalicylic acid)"], dose: "325–650 mg for pain; 81 mg low-dose for heart protection", form: "Tablet or enteric-coated tablet", frequency: "Every 4–6 hours as needed (low-dose: once daily)", route: "Oral", purpose: "Relieves pain, fever and inflammation; low-dose aspirin prevents heart attacks and strokes", side_effects: ["Stomach upset", "Easy bruising", "Heartburn"], warnings: ["Never give to children or teens with viral illness (Reye's syndrome risk)", "Increases bleeding risk — tell your doctor before surgery", "Avoid with other NSAIDs unless your doctor approves"] },

  // ---------- OTC: allergy / cold / cough ----------
  { name: "Claritin", generic_name: "Loratadine", category: "otc", aliases: ["alavert", "loratadine"], active_ingredients: ["Loratadine"], dose: "10 mg", form: "Tablet or dissolvable tablet", frequency: "Once daily", route: "Oral", purpose: "Non-drowsy antihistamine for hay fever, hives and allergy symptoms", side_effects: ["Headache", "Dry mouth", "Mild drowsiness in some people"], warnings: ["Do not exceed one dose a day"] },
  { name: "Zyrtec", generic_name: "Cetirizine", category: "otc", aliases: ["allertec", "cetirizine hcl"], active_ingredients: ["Cetirizine"], dose: "10 mg", form: "Tablet or liquid", frequency: "Once daily", route: "Oral", purpose: "Antihistamine for year-round and seasonal allergies; works faster than loratadine", side_effects: ["Drowsiness in some people", "Dry mouth", "Tiredness"], warnings: ["May cause drowsiness — see how you react before driving"] },
  { name: "Allegra", generic_name: "Fexofenadine", category: "otc", aliases: ["allegra allergy", "fexofenadine hcl"], active_ingredients: ["Fexofenadine"], dose: "60–180 mg", form: "Tablet or gelcap", frequency: "Once or twice daily", route: "Oral", purpose: "Non-drowsy antihistamine for seasonal allergies", side_effects: ["Headache", "Nausea"], warnings: ["Do not take with fruit juice (grapefruit, orange, apple) — it reduces absorption"] },
  { name: "Benadryl", generic_name: "Diphenhydramine", category: "otc", aliases: ["zzzquil", "diphenhydramine hcl", "benadryl ultratab"], active_ingredients: ["Diphenhydramine"], dose: "25–50 mg", form: "Tablet, capsule or liquid", frequency: "Every 4–6 hours as needed (max 300 mg/day)", route: "Oral", purpose: "Fast-acting antihistamine for allergic reactions, itching, hives and occasional sleeplessness", side_effects: ["Drowsiness", "Dry mouth", "Dizziness"], warnings: ["Do not drive after taking", "Avoid combining with alcohol or other sedatives", "Not for nightly sleep use in older adults"] },
  { name: "Flonase", generic_name: "Fluticasone propionate (nasal)", category: "otc", aliases: ["flonase allergy relief", "fluticasone nasal spray"], active_ingredients: ["Fluticasone propionate"], dose: "2 sprays (50 mcg each) per nostril", form: "Nasal spray", frequency: "Once daily", route: "Nasal", purpose: "Steroid nasal spray that relieves congestion, sneezing and sinus pressure from allergies", side_effects: ["Nosebleeds", "Nasal dryness", "Mild headache"], warnings: ["Shake before each use", "Aim away from the nasal septum (center wall)", "Full effect takes several days"] },
  { name: "Mucinex", generic_name: "Guaifenesin", category: "otc", aliases: ["guaifenesin er", "robafen"], active_ingredients: ["Guaifenesin"], dose: "600 mg (12-hour)", form: "Extended-release tablet", frequency: "Every 12 hours with a full glass of water (max 2400 mg/day)", route: "Oral", purpose: "Expectorant that thins and loosens chest mucus so coughs clear it", side_effects: ["Nausea", "Stomach upset", "Dizziness"], warnings: ["Drink plenty of fluids", "Do not crush or chew extended-release tablets"] },
  { name: "Sudafed", generic_name: "Pseudoephedrine", category: "otc", aliases: ["sudafed congestion", "pseudoephedrine hcl"], active_ingredients: ["Pseudoephedrine"], dose: "30–60 mg", form: "Tablet", frequency: "Every 4–6 hours as needed (max 240 mg/day)", route: "Oral", purpose: "Decongestant that shrinks swollen nasal passages from colds and sinus pressure", side_effects: ["Trouble sleeping", "Nervousness", "Fast heartbeat"], warnings: ["Do not take near bedtime", "Ask your doctor before use if you have high blood pressure, heart disease or take MAO inhibitors", "Sold behind the pharmacy counter"] },
  { name: "Delsym", generic_name: "Dextromethorphan", category: "otc", aliases: ["robotussin dm", "dextromethorphan polistirex", "mucinex dm"], active_ingredients: ["Dextromethorphan"], dose: "30 mg (12-hour)", form: "Extended-release liquid or tablet", frequency: "Every 12 hours", route: "Oral", purpose: "Cough suppressant for a dry, hacking cough", side_effects: ["Mild drowsiness", "Stomach upset"], warnings: ["Never combine with MAO inhibitors", "Do not exceed the labeled dose"] },
  { name: "DayQuil", generic_name: "Acetaminophen/dextromethorphan/phenylephrine", category: "otc", active_ingredients: ["Acetaminophen", "Dextromethorphan", "Phenylephrine"], dose: "30 ml liquid or 2 caps (per dose)", form: "Liquid or capsules", frequency: "Every 4 hours as needed (max 4–5 doses/day)", route: "Oral", purpose: "Daytime multi-symptom cold and flu relief — aches, fever, cough, congestion", side_effects: ["Nervousness", "Dizziness", "Trouble sleeping"], warnings: ["Contains acetaminophen — never combine with Tylenol", "Do not combine with other products containing the same ingredients"] },
  { name: "NyQuil", generic_name: "Acetaminophen/dextromethorphan/doxylamine", category: "otc", aliases: ["nyquil cold and flu"], active_ingredients: ["Acetaminophen", "Dextromethorphan", "Doxylamine (antihistamine)"], dose: "30 ml liquid or 2 caps (per dose)", form: "Liquid or capsules", frequency: "Every 6 hours as needed, at night (max 4 doses/day)", route: "Oral", purpose: "Nighttime cold and flu relief — eases aches, fever, cough and helps you sleep", side_effects: ["Drowsiness", "Dry mouth", "Dizziness"], warnings: ["Do not drive after taking", "Contains acetaminophen — never combine with Tylenol", "Do not combine with alcohol"] },

  // ---------- OTC: stomach ----------
  { name: "Pepcid", generic_name: "Famotidine", category: "otc", aliases: ["famotidine", "pepcid complete", "pepcid ac"], active_ingredients: ["Famotidine"], dose: "10–20 mg", form: "Tablet (regular or chewable)", frequency: "Once or twice daily as needed", route: "Oral", purpose: "H2 blocker that reduces stomach acid for heartburn, sour stomach and acid indigestion", side_effects: ["Headache", "Constipation or diarrhea", "Dizziness"], warnings: ["Do not use the maximum dose for more than 14 days without a doctor"] },
  { name: "Tums", generic_name: "Calcium carbonate", category: "otc", aliases: ["tums regular strength", "maalox antacid bar"], active_ingredients: ["Calcium carbonate"], dose: "500–1000 mg (1–2 tablets)", form: "Chewable tablet", frequency: "As needed, up to 7 doses/day", route: "Oral", purpose: "Antacid that neutralizes stomach acid for fast heartburn relief", side_effects: ["Constipation", "Gas", "Belching"], warnings: ["Take other medicines 2 hours apart — calcium blocks absorption", "Ask your doctor before use with kidney stones or kidney disease"] },
  { name: "Pepto-Bismol", generic_name: "Bismuth subsalicylate", category: "otc", aliases: ["kaopectate", "pepto bismol"], active_ingredients: ["Bismuth subsalicylate"], dose: "30 ml liquid or 2 tablets", form: "Liquid, chewable or swallowable tablet", frequency: "Every 30–60 minutes as needed (max 8 doses/day)", route: "Oral", purpose: "Relieves nausea, heartburn, indigestion, upset stomach and diarrhea", side_effects: ["Black tongue or stool (harmless)", "Constipation"], warnings: ["Never give to children or teens with viral illness (Reye's syndrome risk)", "Aspirin-family ingredient — avoid if allergic to aspirin", "Do not combine with aspirin or warfarin without advice"] },
  { name: "Imodium", generic_name: "Loperamide", category: "otc", aliases: ["imodium a-d", "loperamide hcl"], active_ingredients: ["Loperamide"], dose: "2 mg after each loose stool (max 8 mg/day OTC)", form: "Caplet or liquid", frequency: "After each loose stool, as needed", route: "Oral", purpose: "Slows the gut to stop acute, non-infectious diarrhea", side_effects: ["Constipation", "Drowsiness", "Stomach discomfort"], warnings: ["Do not exceed the label dose — higher doses cause serious heart problems", "Do not use if you have fever or bloody/black stools — see a doctor", "Stop if no improvement in 2 days"] },
  { name: "MiraLAX", generic_name: "Polyethylene glycol 3350", category: "otc", aliases: ["peg 3350", "clearlax"], active_ingredients: ["Polyethylene glycol 3350"], dose: "1 capful (17 g) in 8–16 oz of liquid", form: "Powder (dissolves in any drink)", frequency: "Once daily", route: "Oral", purpose: "Osmotic laxative that relieves occasional constipation by keeping water in the stool", side_effects: ["Bloating", "Gas", "Loose stools"], warnings: ["Works in 1–3 days — do not increase the dose for quicker results", "Do not use longer than 7 days without a doctor"] },
  { name: "Colace", generic_name: "Docusate sodium", category: "otc", aliases: ["docusate", "dulcolax stool softener"], active_ingredients: ["Docusate sodium"], dose: "100 mg", form: "Capsule", frequency: "Once or twice daily, with a full glass of water", route: "Oral", purpose: "Stool softener that prevents straining and hard, dry stools", side_effects: ["Stomach upset", "Mild cramping"], warnings: ["Works in 1–3 days", "Drink plenty of fluids"] },
  { name: "Dulcolax", generic_name: "Bisacodyl", category: "otc", aliases: ["bisacodyl ec", "dulcolax laxative"], active_ingredients: ["Bisacodyl"], dose: "5–10 mg", form: "Enteric-coated tablet or suppository", frequency: "Once daily (tablet at bedtime; suppository in 15–60 min)", route: "Oral or rectal", purpose: "Stimulant laxative for occasional constipation relief", side_effects: ["Cramping", "Urgency", "Dizziness"], warnings: ["Do not chew or crush tablets", "Do not take within 1 hour of antacids or milk", "Do not use daily for more than a week"] },

  // ---------- OTC: motion sickness / skin ----------
  { name: "Dramamine", generic_name: "Dimenhydrinate", category: "otc", aliases: ["dramamine original", "dimenhydrinate"], active_ingredients: ["Dimenhydrinate"], dose: "50 mg", form: "Tablet or chewable", frequency: "Every 4–6 hours as needed (max 400 mg/day); take 30–60 min before travel", route: "Oral", purpose: "Prevents and treats motion sickness — nausea, vomiting and dizziness", side_effects: ["Drowsiness", "Dry mouth", "Blurred vision"], warnings: ["Do not drive after taking", "Avoid alcohol and other sedatives"] },
  { name: "Cortizone-10", generic_name: "Hydrocortisone cream 1%", category: "otc", aliases: ["hydrocortisone", "cortaid"], active_ingredients: ["Hydrocortisone (1%)"], dose: "Apply a thin layer to the affected area", form: "Cream, ointment or spray", frequency: "Up to 3–4 times daily", route: "Topical", purpose: "Mild steroid that relieves itching and inflammation from eczema, rashes, insect bites and poison ivy", side_effects: ["Temporary stinging", "Skin thinning with overuse"], warnings: ["Do not use on the face, groin or under diapers unless your doctor says so", "Do not use longer than 7 days", "Do not cover with airtight bandages"] },
  { name: "Neosporin", generic_name: "Bacitracin/neomycin/polymyxin B", category: "otc", aliases: ["neosporin original ointment", "triple antibiotic ointment", "polysporin"], active_ingredients: ["Bacitracin", "Neomycin sulfate", "Polymyxin B"], dose: "Apply a small amount to the cleaned area", form: "Ointment or cream", frequency: "1–3 times daily, covered if needed", route: "Topical", purpose: "First-aid antibiotic ointment that prevents infection in minor cuts, scrapes and burns", side_effects: ["Rare allergic skin rash (neomycin is a common sensitizer)"], warnings: ["Do not use longer than a week", "Stop if a rash appears — neomycin allergy is common", "Seek care for deep or infected wounds"] },
  { name: "Voltaren Arthritis Pain Gel", generic_name: "Diclofenac sodium 1% (topical)", category: "otc", aliases: ["voltaren gel", "diclofenac gel"], active_ingredients: ["Diclofenac sodium"], dose: "2–4 g per joint (per the dosing card)", form: "Topical gel", frequency: "4 times daily", route: "Topical", purpose: "Topical NSAID that relieves arthritis pain in hands, wrists, elbows, feet, ankles and knees", side_effects: ["Skin dryness or irritation at the application site"], warnings: ["Do not combine with oral NSAIDs (ibuprofen, naproxen) without your doctor", "Do not use on broken skin or with a heating pad", "Wash hands after applying"] },

  // ---------- Supplements ----------
  { name: "Melatonin", generic_name: "Melatonin", category: "supplement", active_ingredients: ["Melatonin"], dose: "0.5–5 mg", form: "Tablet, gummy or liquid", frequency: "Once at bedtime, 30–60 minutes before sleep", route: "Oral", purpose: "Helps regulate the sleep-wake cycle for occasional insomnia and jet lag", side_effects: ["Drowsiness", "Vivid dreams", "Morning grogginess"], warnings: ["Do not drive after taking", "Talk to your doctor before use with blood thinners or immune suppressants"] },
  { name: "Vitamin D3", generic_name: "Cholecalciferol", category: "supplement", aliases: ["vitamin d", "cholecalciferol"], active_ingredients: ["Cholecalciferol (Vitamin D3)"], dose: "1000–2000 IU daily (as directed)", form: "Softgel or tablet", frequency: "Once daily with a meal containing fat", route: "Oral", purpose: "Supports bone health, calcium absorption and immune function", side_effects: ["Nausea at very high doses"], warnings: ["Very high doses can raise calcium dangerously — follow the label"] },
  { name: "Vitamin C", generic_name: "Ascorbic acid", category: "supplement", aliases: ["vitamin c", "ascorbic acid", "emergen-c"], active_ingredients: ["Ascorbic acid (Vitamin C)"], dose: "500–1000 mg", form: "Tablet, gummy or effervescent powder", frequency: "Once daily", route: "Oral", purpose: "Supports immune function and collagen production; antioxidant", side_effects: ["Stomach upset at high doses"], warnings: ["Doses over 2000 mg/day can cause diarrhea", "Can interfere with some lab tests"] },
  { name: "Vitamin B12", generic_name: "Cyanocobalamin", category: "supplement", aliases: ["vitamin b12", "methylcobalamin"], active_ingredients: ["Cyanocobalamin (Vitamin B12)"], dose: "500–1000 mcg", form: "Tablet, gummy or sublingual lozenge", frequency: "Once daily", route: "Oral", purpose: "Supports nerve function, red blood cell formation and energy metabolism", side_effects: ["Rare — generally very safe"], warnings: ["Tell your doctor if you take metformin or acid reducers long-term — they lower B12 absorption"] },
  { name: "Calcium + D3", generic_name: "Calcium carbonate with vitamin D", category: "supplement", aliases: ["caltrate", "citracal", "tums as supplement"], active_ingredients: ["Calcium carbonate", "Cholecalciferol (Vitamin D3)"], dose: "500–600 mg calcium per serving", form: "Tablet or chewable", frequency: "Once or twice daily with meals (split doses over 500 mg)", route: "Oral", purpose: "Supports bone density and prevents osteoporosis", side_effects: ["Constipation", "Gas", "Bloating"], warnings: ["Take thyroid medicine (levothyroxine) 4 hours apart", "Take antibiotics (like cipro) 2 hours apart"] },
  { name: "Magnesium", generic_name: "Magnesium (oxide/citrate)", category: "supplement", aliases: ["magnesium citrate", "magnesium glycinate", "magnesium oxide"], active_ingredients: ["Magnesium"], dose: "250–400 mg elemental", form: "Tablet, capsule or powder", frequency: "Once daily, often at night", route: "Oral", purpose: "Supports muscle and nerve function, cramp relief, and regular sleep", side_effects: ["Diarrhea (especially citrate/oxide)", "Stomach upset"], warnings: ["Take 2–4 hours apart from thyroid medicine and some antibiotics", "Ask your doctor before use with kidney disease"] },
  { name: "Fish Oil", generic_name: "Omega-3 (EPA/DHA)", category: "supplement", aliases: ["omega 3", "krill oil", "cod liver oil", "epa dha"], active_ingredients: ["EPA (eicosapentaenoic acid)", "DHA (docosahexaenoic acid)"], dose: "1000 mg (combined EPA/DHA)", form: "Softgel", frequency: "Once or twice daily with meals", route: "Oral", purpose: "Supports heart health and healthy triglycerides; may ease joint stiffness", side_effects: ["Fishy burps", "Stomach upset", "Loose stools"], warnings: ["High doses can increase bleeding — tell your doctor before surgery", "Check with your doctor if you take blood thinners"] },
  { name: "Multivitamin", generic_name: "Multivitamin/mineral supplement", category: "supplement", aliases: ["centrum", "one a day", "womens one a day", "mens daily"], active_ingredients: ["Vitamins A, C, D, E, K, B-complex", "Minerals (zinc, selenium, manganese, etc.)"], dose: "1 tablet or 2 gummies per serving", form: "Tablet, gummy or chewable", frequency: "Once daily with a meal", route: "Oral", purpose: "Fills everyday nutritional gaps in the diet", side_effects: ["Stomach upset", "Constipation (with iron)"], warnings: ["Do not combine multiple vitamin products containing vitamin A or iron", "Keep away from children — iron overdose is dangerous"] },
  { name: "Zinc", generic_name: "Zinc (gluconate/citrate)", category: "supplement", aliases: ["zinc gluconate", "zinc acetate", "cold-eeze"], active_ingredients: ["Zinc"], dose: "15–50 mg", form: "Tablet, lozenge or gummy", frequency: "Once daily; lozenges as needed for colds", route: "Oral", purpose: "Supports immune function; zinc lozenges may shorten colds if started early", side_effects: ["Nausea on an empty stomach", "Metallic taste (lozenges)"], warnings: ["Take with food to avoid nausea", "Long-term high doses can lower copper", "Take 2 hours apart from antibiotics (doxycycline, cipro)"] },
  { name: "Iron", generic_name: "Ferrous sulfate", category: "supplement", aliases: ["ferrous sulfate 325", "ferrous gluconate", "ferrochel"], active_ingredients: ["Ferrous sulfate (65 mg elemental iron)"], dose: "325 mg (65 mg elemental)", form: "Tablet", frequency: "Once daily or as prescribed", route: "Oral", purpose: "Treats and prevents iron-deficiency anemia", side_effects: ["Constipation", "Dark stools", "Stomach upset"], warnings: ["Take with vitamin C to boost absorption; separate from coffee, tea, dairy and calcium by 2 hours", "Keep away from children — iron overdose is dangerous"] },
  { name: "Probiotic", generic_name: "Probiotic blend", category: "supplement", aliases: ["lactobacillus", "acidophilus", "bifidobacterium", "align", "culturelle", "florastor"], active_ingredients: ["Lactobacillus species", "Bifidobacterium species"], dose: "1 capsule or sachet (5–50 billion CFU)", form: "Capsule, tablet or sachet", frequency: "Once daily, with or just after a meal", route: "Oral", purpose: "Supports gut health, digestion and recovery after antibiotics", side_effects: ["Mild gas or bloating the first days"], warnings: ["Ask your doctor before use if you have a weakened immune system"] },
  { name: "CoQ10", generic_name: "Coenzyme Q10", category: "supplement", aliases: ["coenzyme q10", "ubiquinol", "ubiquinone"], active_ingredients: ["Coenzyme Q10"], dose: "100–200 mg", form: "Softgel", frequency: "Once daily with a meal containing fat", route: "Oral", purpose: "Supports cellular energy; often taken alongside statins and for heart health", side_effects: ["Stomach upset", "Insomnia if taken late"], warnings: ["May reduce the effect of warfarin — tell your doctor", "Take in the morning"] },
  { name: "Glucosamine + Chondroitin", generic_name: "Glucosamine/chondroitin sulfate", category: "supplement", aliases: ["glucosamine chondroitin msm", "osteo bi-flex"], active_ingredients: ["Glucosamine sulfate", "Chondroitin sulfate"], dose: "1500 mg / 1200 mg daily", form: "Tablet or capsule", frequency: "Once daily or split", route: "Oral", purpose: "Supports joint comfort and cartilage health in osteoarthritis", side_effects: ["Mild stomach upset", "Heartburn"], warnings: ["Often made from shellfish — avoid with shellfish allergy unless labeled otherwise", "May affect blood sugar — monitor if diabetic", "May increase the effect of warfarin"] },
  { name: "Turmeric Curcumin", generic_name: "Curcumin (turmeric extract)", category: "supplement", aliases: ["curcumin", "turmeric", "curcumin c3 complex"], active_ingredients: ["Curcuminoids (curcumin)"], dose: "500–1000 mg (with black pepper extract for absorption)", form: "Capsule or tablet", frequency: "Once or twice daily with meals", route: "Oral", purpose: "Antioxidant used for joint comfort and general inflammation support", side_effects: ["Stomach upset at high doses"], warnings: ["May increase bleeding risk — tell your doctor before surgery", "Check with your doctor if you take blood thinners or gallbladder issues"] },
];

// Normalize a string for matching: lowercase and strip everything that isn't a
// letter or digit, so "Advil Liqui-Gels", "advil" and "advil." all match.
function norm(s) {
  return String(s || "").toLowerCase().replace(/[^a-z0-9]/g, "");
}

// Total number of medications in the offline guide (shown in the UI).
export const drugCount = DRUGS.length;

// Search the offline guide by brand name, generic name, alias or active
// ingredient. Returns the best matches, highest score first.
//   100 = exact name match    60 = name starts with the query
//    30 = name contains it   20 = the query contains the name
export function searchDrugs(query, limit = 8) {
  const q = norm(query);
  if (!q || q.length < 2) return [];
  const scored = [];
  for (const d of DRUGS) {
    const candidates = [d.name, d.generic_name, ...(d.aliases || []), ...(d.active_ingredients || [])];
    let score = 0;
    for (const c of candidates) {
      const n = norm(c);
      if (!n) continue;
      if (n === q) score = Math.max(score, 100);
      else if (n.startsWith(q)) score = Math.max(score, 60);
      else if (n.includes(q)) score = Math.max(score, 30);
      else if (n.length >= 4 && q.includes(n)) score = Math.max(score, 20);
    }
    if (score > 0) scored.push({ d, score });
  }
  scored.sort((a, b) => b.score - a.score || a.d.name.localeCompare(b.d.name));
  return scored.slice(0, limit).map((x) => x.d);
}